---
collection_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | dirname }}"
integration_tests_path: "{{ collection_root }}/tests/integration/targets/"
test_name: "{{ lookup('env', 'MOLECULE_SCENARIO_NAME') | replace('integration_', '') }}"
